config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "hello#index"

  #mypage関するページ
  get "/mypage/index" => "mypage#index"



  #投稿ページ表示
  get "/practices/new" => "practices#new"
  #投稿し、ホームにリダイレクト
  post "/practices/new" => "practices#create"
  #投稿一覧
  get "/practices/index" => "practices#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/practice.rb
class Practice < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def index
    @str = "Mypage"
  end
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController

  #全ての投稿を表示する画面
  def index
    @tweets = Tweet.all
  end

  #新しいTweetの保存
  def create
    @tweet = Tweet.new(tweet_params)

    #新しいTweetの保存に成功した場合
    if @tweet.save
      #index.html.erbにページが移る
      redirect_to action: "index"
    #新しいTweetの保存に失敗した場合
    else
      #もう一回投稿画面へ
      redirect_to action: "new"
    end
  end

  private
  #セキュリティのため、許可した:bodyというデータだけ取ってくるようにする
  def tweet_params
    params.require(:tweet).permit(:body)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/hello/index.html.erb
<!-- <%= button_to "マイページへ", { :controller => "mypage", :action => "index"}, :method => :get %>

<%= button_to "ログイン", { :controller => "mypage", :action => "index"}, :method => :get %>

<%= button_to "新規登録", { :controller => "devise/registrations", :action => "new"}, :method => :get %> -->


<!DOCTYPE HTML>
<!--
	Retrospect by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>練習日誌(仮) Top Page</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/stylesheets/main.css" />
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
	</head>
	<body class="landing">

		<!-- Header -->
			<header id="header" class="alt">
				<h1><a href="index.html">練習日誌(仮)</a></h1>
				<nav><a href="#one">About</a></nav>
				<nav><a href="#two">機能</a></nav>
				<nav><a href="#four">ご意見</a></nav>
				<a href="#nav">Menu</a>
			</header>

		<!-- Nav -->
			<nav id="nav">
				<ul class="links">
					<li><a href="index.html">Home</a></li>
					<li><a href="generic.html">Generic</a></li>
					<li><a href="elements.html">Elements</a></li>
				</ul>
			</nav>

		<!-- Banner -->
			<section id="banner">
				<i class="icon fa-diamond"></i>
				<h2>練習日誌(仮)</h2>
				<p>中長距離アスリートのための練習日誌＆意見交換サービス</p>
				<ul class="actions">
					<li><a href="#" class="button big alt">新規登録</a></li>
					<li><a href="#" class="button big special">ログイン</a></li>
				</ul>
			</section>

		<!-- One -->
			<section id="one" class="wrapper special">
				<div class="inner">
					<header class="major narrow">
						<h2>About</h2>
						<p>記録を狙うランナーにとって、試合や練習の結果を記録し、分析することは非常に重要です。練習日誌(仮)はそんなランナー達をサポートする練習日誌&意見交換サービスです。</p>
					</header>
					<div class="image-grid">
						<a href="#" class="image"><img src="assets/pic03.jpg" alt="" /></a>
						<a href="#" class="image"><img src="assets/pic04.jpg" alt="" /></a>
						<a href="#" class="image"><img src="assets/pic05.jpg" alt="" /></a>
						<a href="#" class="image"><img src="assets/pic06.jpg" alt="" /></a>
						<a href="#" class="image"><img src="assets/pic07.jpg" alt="" /></a>
						<a href="#" class="image"><img src="assets/pic08.jpg" alt="" /></a>
						<a href="#" class="image"><img src="assets/pic09.jpg" alt="" /></a>
						<a href="#" class="image"><img src="assets/pic10.jpg" alt="" /></a>
					</div>
					<ul class="actions">
						<li><a href="#" class="button big alt">今すぐ練習日誌を書く</a></li>
					</ul>
				</div>
			</section>

		<!-- Two -->
			<section id="two" class="wrapper style1">
				<div class="inner">
					<header>
						<h2>機能</h2>
					</header>
					<article class="feature left">
						<span class="image"><img src="assets/kinou1.png" alt="" /></span>
						<div class="content">
							<h2>見やすいマイページ機能</h2>
							<p>自分の練習日誌をカレンダー形式で表示。次のレースまであと何日か、自分が過去にどんな練習をしてきたのかが見やすく表示されます。。</p>
							<ul class="actions">
								<li>
									<a href="#" class="button alt">マイページへ</a></a>
								</li>
							</ul>
						</div>
					</article>
					<article class="feature right">
						<span class="image"><img src="assets/kinou2.png" alt="" /></span>
						<div class="content">
							<h2>豊富な記録項目</h2>
							<p>天気や練習タイム、その日の反省等の基本的な項目はもちろん、食事内容、睡眠時間、満足度等様々な項目を記録可能。自分で追加もできます。</p>
							<ul class="actions">
								<li>
									<a href="#" class="button alt">練習日誌を書く</a>
								</li>
							</ul>
						</div>
					</article>
					<article class="feature left">
						<span class="image"><img src="assets/kinou3.png" alt="" /></span>
						<div class="content">
							<h2>データをグラフで分析</h2>
							<p>これまでに記録した練習日誌のデータを見やすく可視化。日ごとの体重変化から月間走行距離の推移まで、可視化することで自分の成長が一目でわかります。</p>
							<ul class="actions">
								<li>
									<a href="#" class="button alt">練習日誌を見る</a>
								</li>
							</ul>
						</div>
					</article>
					<!-- <article class="feature right">
						<span class="image"><img src="images/pic02.jpg" alt="" /></span>
						<div class="content">
							<h2>他のランナーとの意見交換</h2>
							<p>普段は一人で練習しているランナーも、他のランナーと様々な意見を交換できます。</p>
							<ul class="actions">
								<li>
									<a href="#" class="button alt">チャットへ</a>
								</li>
							</ul>
						</div>
					</article> -->
				</div>
			</section>


		<!-- Three -->
			<!-- <section id="three" class="wrapper style3 special">
				<div class="inner">
					<header class="major narrow	">
						<h2>about</h2>
						<p>記録を狙うランナーにとって、試合や練習の結果を記録し、分析することは非常に重要です。練習日誌(仮)はそんなランナー達をサポートする練習日誌、意見交換サービスです。</p>
					</header>
					<ul class="actions">
						<li><a href="#" class="button big alt">Magna feugiat</a></li>
					</ul>
				</div>
			</section> -->

		<!-- Four -->
			<section id="four" class="wrapper style2 special">
				<div class="inner">
					<header class="major narrow">
						<h2>ご意見等はこちら</h2>
						<p>以下のフォームにお気づきの点をご入力ください</p>
					</header>
					<form action="#" method="POST">
						<div class="container 75%">
							<div class="row uniform 50%">
								<div class="6u 12u$(xsmall)">
									<input name="name" placeholder="お名前（ニックネーム）" type="text" />
								</div>
								<div class="6u$ 12u$(xsmall)">
									<input name="email" placeholder="Email" type="email" />
								</div>
								<div class="12u$">
									<textarea name="message" placeholder="ご意見" rows="4"></textarea>
								</div>
							</div>
						</div>
						<ul class="actions">
							<li><input type="submit" class="special" value="送る" /></li>
							<li><input type="reset" class="alt" value="全て消す" /></li>
						</ul>
					</form>
				</div>
			</section>

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">
					<!-- <ul class="icons">
						<li><a href="#" class="icon fa-facebook">
							<span class="label">Facebook</span>
						</a></li>
						<li><a href="#" class="icon fa-twitter">
							<span class="label">Twitter</span>
						</a></li>
						<li><a href="#" class="icon fa-instagram">
							<span class="label">Instagram</span>
						</a></li>
						<li><a href="#" class="icon fa-linkedin">
							<span class="label">LinkedIn</span>
						</a></li>
					</ul> -->
					<ul class="copyright">
						<li>&copy; Untitled.</li>
						<li>Images: <a href="http://unsplash.com">Unsplash</a>.</li>
						<li>Design: <a href="http://templated.co">TEMPLATED</a>.</li>
					</ul>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="assets/javascripts/jquery.min.js"></script>
			<script src="assets/javascripts/skel.min.js"></script>
			<script src="assets/javascripts/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/javascripts/main.js"></script>

	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyService</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mypage/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <h1>マイページ</h1>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>